FROM ghcr.io/void-linux/void-mklive:latest

ARG MIRROR="https://repo-fastly.voidlinux.org/"

RUN xbps-install -SyuR "${MIRROR}/current" xbps \
	&& xbps-install -yuR "${MIRROR}/current" \
	&& xbps-install -yR "${MIRROR}/current" nodejs \
	&& xbps-remove -Oo \
	&& rm -rf /var/cache/xbps/*

CMD ["/bin/bash"]
