---
displaymanagers:
  - lightdm

defaultDesktopEnvironment:
    executable: "startxfce4"
    desktopFile: "xfce4-session"

basicSetup: false
sysconfigSetup: false

lightdm:
  preferred_greeters: ["lightdm-gtk-greeter.desktop"]
