name: Build void images

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-live-isos:
    name: Build Live ISOs
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        flavor: [xfce, kde, gnome]

    container:
      image: "ghcr.io/void-linux/void-mklive:20250116R1"
      options: --privileged
      volumes:
        - /dev:/dev
      env:
        PATH: "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin"

    steps:
      - name: Prepare container
        shell: sh
        run: xbps-install -Syu xbps && xbps-install -yu

      - name: Clone and checkout
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Build live ISOs
        run: |
          make live-iso-all-print live-iso-all \
            SUDO= LIVE_FLAVORS="${{ matrix.flavor }}"

      - name: TEST
        run: ls -lah
